name: Python application

on:
  push:
   branches: [ master ]
  pull_request:
    branches: [ master ]
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        echo "${{ secrets.DOCKERPWD }}" | docker login -u "roshan2346" --password-stdin
        docker image build -t roshan2346/python_app:latest .
        docker push roshan2346/python_app:latest